name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.12
  NODE_VERSION: 18
  NODE_ENV: ci
  CI: true

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  libx-py:
    runs-on: ubuntu-22.04
    needs: cancel-previous-runs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Python
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --dev

      - name: Linter
        run: |
          python -m black libx/*.py -l 80 --check

  libx-js:
    runs-on: ubuntu-22.04
    needs: cancel-previous-runs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
        working-directory: www/libx

      - name: Yarn Install
        run: |
          yarn install
        working-directory: www/libx

      - name: Yarn Lint
        run: |
          yarn lint
        working-directory: www/libx

      - name: Yarn Pretty
        run: |
          yarn pretty
        working-directory: www/libx

      - name: Yarn Build
        run: |
          yarn build
        working-directory: www/libx